class Product {
  int? id;
  String name;

  Product({
    this.id,
    required this.name,
  });

  /// Converts a [Product] instance into a [Map] for database operations.
  /// The 'id' is intentionally omitted because it is auto-generated by the
  /// database and should not be included in insert/update operations.
  Map<String, dynamic> toMap() {
    return {
      'name': name,
    };
  }

  /// Creates a [Product] instance from a [Map].
  factory Product.fromMap(Map<String, dynamic> map) {
    return Product(
      id: map['id'] as int?,
      name: map['name'] as String,
    );
  }
}
